# Generated by Django 5.0.1 on 2024-02-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=350)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_amount', models.PositiveIntegerField()),
                ('product_reg_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
