# Generated by Django 5.0.1 on 2024-02-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0004_product_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='processing', max_length=30),
        ),
    ]
